services:
  - type: web
    name: task-management-api
    env: node
    region: singapore # or choose a region closer to your users
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DB_TYPE
        value: postgres
      - key: DATABASE_URL
        value: postgresql://task_management_user:x5vFjWQ2a9lduTWzxc2KqYSN6oHBarNq@dpg-cvqdsq3e5dus73f841ig-a/task_management_uo51
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h

databases:
  - name: task-management-db
    databaseName: task_management
    user: task_management_user
    plan: free
    region: singapore
    ipAllowList: [] # optional (allows all)
